[pytest]
asyncio_mode = auto
pythonpath = src
testpaths = tests

filterwarnings =
    error
    ignore::DeprecationWarning
    ignore:'crypt' is deprecated and slated for removal in Python 3.13:DeprecationWarning

addopts =
    --cov=src/blogcache
    --cov-report=term-missing
    --cov-report=html
    --cov-fail-under=75
    --strict-markers
    -v
